name: Package

on: workflow_dispatch

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download language server
        run: |
          ver=$(curl -s https://api.github.com/repos/VHDL-LS/rust_hdl/releases/latest | grep -oP '"tag_name": "v\K(.*)(?=")')
          wget -P temp https://github.com/VHDL-LS/rust_hdl/releases/latest/download/vhdl_ls-x86_64-unknown-linux-musl.zip
          wget -P temp https://github.com/VHDL-LS/rust_hdl/releases/latest/download/vhdl_ls-x86_64-pc-windows-msvc.zip
          mkdir --parents server/vhdl_ls/$ver
          unzip temp/vhdl_ls-x86_64-unknown-linux-musl.zip -d server/vhdl_ls/$ver
          unzip temp/vhdl_ls-x86_64-pc-windows-msvc.zip -d server/vhdl_ls/$ver
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install NPM packages
        run: |
          npm install
          npm install -g vsce
      - run: vsce package
      - run: mkdir vhdl-ls && cp *.vsix vhdl-ls
      - uses: actions/upload-artifact@v4
        with:
          name: vhdl-ls
          path: vhdl-ls
